# Generated by Django 4.0.3 on 2022-09-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DChampionship',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('D', 'Départemental'), ('R', 'Régional')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'd_championships',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DClub',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('departement', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_clubs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DCompetition',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('championship', models.ForeignKey(db_column='championship', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dchampionship')),
            ],
            options={
                'db_table': 'd_competitions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPlayer',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Masculins'), ('F', 'Féminines')], max_length=1)),
                ('club', models.ForeignKey(db_column='club', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dclub')),
            ],
            options={
                'db_table': 'd_players',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPool',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=31)),
                ('age', models.CharField(choices=[('00', 'Senior'), ('01', 'Senior'), ('02', 'Senior'), ('10', 'Senior'), ('35', '-18'), ('40', '-17'), ('45', '-16'), ('50', '-15'), ('55', '-14'), ('60', '-13'), ('65', '-12'), ('70', '-11'), ('75', '-10'), ('80', '-9'), ('85', 'Mini-Hand')], max_length=2)),
                ('gender', models.CharField(choices=[('Z', 'Mixte'), ('M', 'Masculins'), ('F', 'Féminines')], max_length=1)),
                ('pool_hash', models.CharField(default='', max_length=32)),
                ('player_hash', models.CharField(default='', max_length=32)),
                ('competition', models.ForeignKey(db_column='competition', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dcompetition')),
            ],
            options={
                'db_table': 'd_pools',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPoolDate',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('pool', models.ForeignKey(db_column='pool', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dpool')),
            ],
            options={
                'db_table': 'd_pool_dates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPoolTeam',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('defeats', models.IntegerField(blank=True, null=True)),
                ('scored', models.IntegerField(blank=True, null=True)),
                ('missed', models.IntegerField(blank=True, null=True)),
                ('difference', models.IntegerField(blank=True, null=True)),
                ('pool', models.ForeignKey(db_column='pool', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dpool')),
            ],
            options={
                'db_table': 'd_pool_teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPoolPlayerStat',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('game', models.IntegerField(blank=True, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('mins', models.IntegerField(blank=True, null=True)),
                ('warn', models.IntegerField(blank=True, null=True)),
                ('dis', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dplayer')),
                ('pool', models.ForeignKey(db_column='pool', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dpool')),
            ],
            options={
                'db_table': 'd_pool_player_stats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPoolPlayer',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('match_played', models.IntegerField(blank=True, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('avg_stop', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(db_column='player', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dplayer')),
                ('pool', models.ForeignKey(db_column='pool', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dpool')),
            ],
            options={
                'db_table': 'd_pool_players',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DPoolEvent',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('date_day', models.IntegerField(blank=True, null=True)),
                ('date_date', models.DateField(blank=True, null=True)),
                ('date_hour', models.IntegerField(blank=True, null=True)),
                ('date_minute', models.IntegerField(blank=True, null=True)),
                ('team_0_name', models.CharField(max_length=255)),
                ('team_0_score', models.CharField(blank=True, max_length=2, null=True)),
                ('team_1_name', models.CharField(max_length=255)),
                ('team_1_score', models.CharField(blank=True, max_length=2, null=True)),
                ('referee_0_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referee_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_0', models.CharField(blank=True, max_length=255, null=True)),
                ('location_1', models.CharField(blank=True, max_length=255, null=True)),
                ('location_2', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=31)),
                ('fdm', models.CharField(max_length=255)),
                ('date', models.ForeignKey(db_column='date', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dpooldate')),
                ('pool', models.ForeignKey(db_column='pool', on_delete=django.db.models.deletion.DO_NOTHING, to='hbsui.dpool')),
            ],
            options={
                'db_table': 'd_pool_events',
                'managed': True,
            },
        ),
    ]
