# Generated by Django 4.0.3 on 2023-01-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbsui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dplayer',
            name='avg_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='avg_save',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='dis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dplayer',
            name='warn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
