# Generated by Django 4.0.3 on 2023-01-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbsui', '0002_dplayer_avg_goal_dplayer_avg_save_dplayer_dis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dplayer',
            old_name='avg_goal',
            new_name='avg_goals',
        ),
        migrations.RenameField(
            model_name='dplayer',
            old_name='avg_save',
            new_name='avg_saves',
        ),
        migrations.RenameField(
            model_name='dplayer',
            old_name='game',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='dplayer',
            old_name='goal',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='dplayer',
            old_name='save',
            new_name='saves',
        ),
    ]
